language: java
sudo: false
jdk:
- openjdk6
- openjdk7
- oraclejdk7
- oraclejdk8
install: echo "No need to run mvn install -DskipTests then mvn install.  Running mvn
  install."
script: mvn install
env:
  global:
  - STORMPATH_API_KEY_ID=58J8VBZG5WK9CYTEYPZSQX670
  - secure: ZAs6XDgRX1YIZAKf0IcR6DlfQtGLKJS5fyTOextZsRW3MCwu7WTBe5v6dAS6xoLqZ0iEkICMdIRhs+6DQEW6rju/W39mjxe8HJEcMNI+wZyW+rZ+j7NmPkjovMO+XbiR0aVVvn7ZGjWEKdozCTBVtJSLd8YVHh6Ey+yxOdDoc1A=
before_install:
- openssl aes-256-cbc -K $encrypted_da634cfd642b_key -iv $encrypted_da634cfd642b_iv
  -in deployKey_stormpath_github_io_id_rsa.enc -out deployKey_stormpath_github_io_id_rsa
  -d
