# https://travis-ci.org/stormpath/stormpath-sdk-java
language: java

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7

# This API Key is Les's, associated with his personal Stormpath tenant
# (the API Key secret is encrypted here of course):
env:
  - STORMPATH_API_KEY_ID=CN5D6CEHMI7M1HVSBW74N626X
  - secure: "oucE3h/zBYoRfmKXeiG6PTYPWzQCTCpEb3hz2OaE18fC3YbaPS+b/YQGno+gKPMByss4fPytuo9/yFdGPjznwpb5fAQlM/i98lfQtD2ComDTH9a/D9TM3rFrh74EZ7SwvlxRhVOodlx8X5h43oPjloVdB8ZHVFMvkwKR/bMtUeA="
