language: java
sudo: false
jdk:
  #- openjdk6
  #- openjdk7
  #- oraclejdk7
- oraclejdk8

install: echo "No need to run mvn install -DskipTests then mvn install.  Running mvn install."
script: mvn install
env:
  global:
  - STORMPATH_API_KEY_ID=58J8VBZG5WK9CYTEYPZSQX670
  - secure: ZAs6XDgRX1YIZAKf0IcR6DlfQtGLKJS5fyTOextZsRW3MCwu7WTBe5v6dAS6xoLqZ0iEkICMdIRhs+6DQEW6rju/W39mjxe8HJEcMNI+wZyW+rZ+j7NmPkjovMO+XbiR0aVVvn7ZGjWEKdozCTBVtJSLd8YVHh6Ey+yxOdDoc1A=
before_install:
- openssl aes-256-cbc -K $encrypted_da634cfd642b_key -iv $encrypted_da634cfd642b_iv
  -in deployKey_stormpath_github_io_id_rsa.enc -out ~/.ssh/id_rsa
  -d
- chmod 600 ~/.ssh/id_rsa
after_success:
  - test -z "$BUILD_DOCS" || pip install --user sphinx
  - test -z "$BUILD_DOCS" || cd docs
  - test -z "$BUILD_DOCS" || make html
  - test -z "$BUILD_DOCS" || cd ..
  - test -z "$BUILD_DOCS" || git clone git@github.com:stormpath/stormpath.github.io.git
  - test -z "$BUILD_DOCS" || cd stormpath.github.io
  - test -z "$BUILD_DOCS" || git checkout source
  - test -z "$BUILD_DOCS" || cd source/java/servlet-plugin/
  - test -z "$BUILD_DOCS" || cp -p -r ../../../../docs/build/html/* .
  - test -z "$BUILD_DOCS" || cd ../../../
  - test -z "$BUILD_DOCS" || git config --global user.email "java@stormpath.com"
  - test -z "$BUILD_DOCS" || git config --global user.name "Java SDK Auto Doc Build"
  - test -z "$BUILD_DOCS" || git add -A .
  - test -z "$BUILD_DOCS" || git commit -m "Java SDK Auto Doc Build"
  - test -z "$BUILD_DOCS" || git push 
  - test -z "$BUILD_DOCS" || cd ..
matrix:
  include:
    - env: BUILD_DOCS=true
      jdk: 'oraclejdk8'
