language: java
dist: precise
addons:
  apt:
    packages:
      - xsltproc
before_install:
  - source ./ci/before_install.sh
  - source ./ci/stormpath_env.sh
install:
  - ./ci/install.sh
script:
  - ./ci/build.sh
after_success:
  - ./ci/after_success.sh
notifications:
  slack:
    secure: INiA7V4aXvimkImaErVH94ZSmFNuOgun9aurmf3BiE2Qq0EfNiEaWK9pp6hfkv+wSls4LXNDLaYVzdoMECVLh+Dv9VLHIABnaNEmMStXUlyZ+sOpdayl/47gnNr0G1cr06eqbikGVqWtQaxDz2Psaejq2D/6WYw5Vnqk4BjWQHw=

matrix:
  include:
    - os: linux
      sudo: required
      jdk: openjdk7
    - os: linux
      sudo: false
      dist: precise
      jdk: oraclejdk7
    - os: linux
      sudo: false
      dist: precise
      jdk: oraclejdk8